// src/pages/Dashboard.vue
<template>
  <div class="dashboard">
    <a-card title="监控状态">
      <a-table
        :columns="columns"
        :data-source="livers"
        :loading="isLoading"
        :pagination="false"
        rowKey="uid"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'status'">
            <a-tag :color="record.is_live ? 'success' : 'default'">
              {{ record.is_live ? '直播中' : '未开播' }}
            </a-tag>
          </template>
          <template v-if="column.key === 'title'">
            <span v-if="record.title">{{ record.title }}</span>
            <span v-else>-</span>
          </template>
          <template v-if="column.key === 'actions'">
            <a-button 
              type="link" 
              :href="`https://live.bilibili.com/${record.room_id}`" 
              target="_blank"
              v-if="record.room_id"
            >
              查看直播间
            </a-button>
          </template>
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useQuery, useQueryClient } from '@tanstack/vue-query';
import request from '@/utils/request';
import type { MonitorStatus } from '@/types/api';
import { QueryKeys } from '@/constants/queryKeys';

const queryClient = useQueryClient();

const columns = [
  {
    title: 'UID',
    dataIndex: 'uid',
    key: 'uid',
  },
  {
    title: '主播',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '状态',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: '标题',
    dataIndex: 'title',
    key: 'title',
    ellipsis: true,
  },
  {
    title: '操作',
    key: 'actions',
  },
];

const { data: monitorData, isLoading } = useQuery({
  queryKey: QueryKeys.MONITOR_STATUS,
  queryFn: () => request.get<MonitorStatus>('/monitor/status'),
  refetchInterval: 10000,
});

// 当订阅列表更新时，刷新监控状态
queryClient.invalidateQueries({ queryKey: QueryKeys.MONITOR_STATUS });

const livers = computed(() => {
  if (!monitorData.value?.status_cache) return [];
  return Object.entries(monitorData.value.status_cache).map(([uid, status]) => ({
    uid,
    ...status,
    is_live: status.status === 1,
  }));
});
</script>

// src/pages/Dashboard.tsx
import React from 'react';
import { Card, Table, Tag, Button, Space } from 'antd';
import { useQuery } from '@tanstack/react-query';
import request from '../utils/request';
import type { MonitorStatus } from '../types/api';

const Dashboard: React.FC = () => {
  const { data: monitorData, refetch } = useQuery<MonitorStatus>({
    queryKey: ['monitor'],
    queryFn: async () => {
      const response = await request.get<MonitorStatus>('/monitor/status');
      return response;
    },
    refetchInterval: 10000, // 每10秒刷新一次
  });

  // 转换数据格式以适应表格
  const livers = React.useMemo(() => {
    if (!monitorData?.status_cache) return [];
    return Object.entries(monitorData.status_cache).map(([uid, status]) => ({
      uid,
      ...status,
      is_live: status.status === 1
    }));
  }, [monitorData]);

  const columns = [
    {
      title: 'UID',
      dataIndex: 'uid',
      key: 'uid',
    },
    {
      title: '主播',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: '房间号',
      dataIndex: 'room_id',
      key: 'room_id',
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: (status: number) => {
        let color = 'default';
        let text = '未知';
        switch (status) {
          case 1:
            color = 'success';
            text = '直播中';
            break;
          case 2:
            color = 'default';
            text = '未开播';
            break;
          case 0:
            color = 'warning';
            text = '未初始化';
            break;
        }
        return <Tag color={color}>{text}</Tag>;
      },
    },
    {
      title: '标题',
      dataIndex: 'title',
      key: 'title',
      ellipsis: true,
    },
    {
      title: '最后更新',
      dataIndex: 'timestamp',
      key: 'timestamp',
      render: (timestamp: number) => new Date(timestamp * 1000).toLocaleString(),
    }
  ];

  return (
    <Space direction="vertical" style={{ width: '100%' }}>
      <Card 
        title="监控列表" 
        extra={
          <Button type="primary" onClick={() => refetch()}>
            刷新
          </Button>
        }
      >
        <Table 
          columns={columns} 
          dataSource={livers} 
          rowKey="uid"
          pagination={false}
        />
      </Card>
    </Space>
  );
};

export default Dashboard;
