// src/pages/Subscribers.tsx
import React from 'react';
import { Card, Table, Button, Input, Space, Popconfirm, message, Tag, Result } from 'antd';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import request from '../utils/request';
import { useMediaQuery } from '../hooks/useMediaQuery';
import type { LiverInfo } from '../types/api';

interface Subscriber extends LiverInfo {
  mid: string;
  status: string;
}

const Subscribers: React.FC = () => {
  const [newMid, setNewMid] = React.useState('');
  const isMobile = useMediaQuery('(max-width: 768px)');
  const queryClient = useQueryClient();

  // 获取订阅列表
  const { data: subscribers = [], isLoading, error } = useQuery<Subscriber[]>({
    queryKey: ['subscribers'],
    queryFn: async () => {
      const response = await request.get<any[]>('/monitor/subscribers');
      return response.map((sub: any) => ({
        ...sub,
        uid: parseInt(sub.mid),
        is_live: sub.status === '1',
        live_status: sub.status === '1' ? 1 : 0
      }));
    },
    retry: 3,
    staleTime: 30000,
  });

  // 添加订阅
  const addSubscriber = useMutation({
    mutationFn: async (mid: string) => {
      try {
        const response = await request.post(`/monitor/subscribers/${mid}`);
        return response;
      } catch (error: any) {
        message.error(error.message || '添加失败');
        throw error;
      }
    },
    onSuccess: () => {
      message.success('添加成功');
      setNewMid('');
      queryClient.invalidateQueries({ queryKey: ['subscribers'] });
    }
  });

  // 移除订阅
  const removeSubscriber = useMutation({
    mutationFn: async (mid: string) => {
      try {
        const response = await request.delete(`/monitor/subscribers/${mid}`);
        return response;
      } catch (error: any) {
        message.error(error.message || '移除失败');
        throw error;
      }
    },
    onSuccess: () => {
      message.success('移除成功');
      queryClient.invalidateQueries({ queryKey: ['subscribers'] });
    }
  });

  const handleAdd = () => {
    if (!newMid) {
      message.error('请输入UID');
      return;
    }
    if (!/^\d+$/.test(newMid)) {
      message.error('UID必须是数字');
      return;
    }
    addSubscriber.mutate(newMid);
  };

  const columns = [
    {
      title: 'UID',
      dataIndex: 'uid',
      key: 'uid',
      width: isMobile ? 100 : 120,
    },
    {
      title: '主播',
      dataIndex: 'name',
      key: 'name',
      width: isMobile ? 120 : 150,
      render: (name: string, record: Subscriber) => (
        <Space>
          {record.face && (
            <img 
              src={record.face} 
              alt={name} 
              style={{ 
                width: 24, 
                height: 24, 
                borderRadius: '50%',
                marginRight: 8
              }} 
            />
          )}
          {name || '未获取到名称'}
        </Space>
      ),
    },
    {
      title: '状态',
      key: 'status',
      width: 100,
      render: (_: any, record: Subscriber) => {
        let color = 'default';
        let text = '未知';
        if (record.is_live) {
          color = 'success';
          text = '直播中';
        } else if (record.live_status === 0) {
          color = 'default';
          text = '未开播';
        }
        return (
          <Space>
            <Tag color={color}>{text}</Tag>
            {record.is_live && record.title && (
              <span style={{ fontSize: '12px', color: '#666' }}>
                {record.title}
              </span>
            )}
          </Space>
        );
      },
    },
    {
      title: '操作',
      key: 'action',
      width: 100,
      render: (_: any, record: Subscriber) => (
        <Popconfirm
          title="确定要移除吗？"
          onConfirm={() => removeSubscriber.mutate(record.mid)}
        >
          <Button type="link" danger>
            移除
          </Button>
        </Popconfirm>
      ),
    },
  ];

  if (error) {
    return (
      <Card>
        <Result
          status="error"
          title="加载失败"
          subTitle={String(error)}
          extra={
            <Button 
              type="primary" 
              onClick={() => queryClient.invalidateQueries({ queryKey: ['subscribers'] })}
            >
              重试
            </Button>
          }
        />
      </Card>
    );
  }

  return (
    <Space direction="vertical" style={{ width: '100%' }} size="large">
      <Card title="添加订阅">
        <Space.Compact style={{ width: '100%' }}>
          <Input
            placeholder="请输入主播UID"
            value={newMid}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewMid(e.target.value)}
            onPressEnter={handleAdd}
          />
          <Button 
            type="primary" 
            onClick={handleAdd}
            loading={addSubscriber.isPending}
          >
            添加
          </Button>
        </Space.Compact>
      </Card>

      <Card 
        title="订阅列表" 
        extra={
          <Button 
            onClick={() => queryClient.invalidateQueries({ queryKey: ['subscribers'] })}
            loading={isLoading}
          >
            刷新
          </Button>
        }
      >
        <Table
          columns={columns}
          dataSource={subscribers}
          rowKey="uid"
          loading={isLoading}
          pagination={false}
          scroll={{ x: isMobile ? 500 : undefined }}
        />
      </Card>
    </Space>
  );
};

export default Subscribers;

// src/pages/Subscribers.vue
<template>
  <div class="subscribers">
    <a-card title="添加订阅">
      <a-space>
        <a-input
          v-model:value="newMid"
          placeholder="请输入主播UID"
          style="width: 200px"
          @keyup.enter="handleAdd"
          :disabled="isAdding"
        />
        <a-button 
          type="primary" 
          :loading="isAdding" 
          @click="handleAdd"
        >
          添加
        </a-button>
      </a-space>
    </a-card>

    <a-card 
      title="订阅列表" 
      style="margin-top: 16px"
    >
      <template #extra>
        <a-button 
          @click="handleRefresh" 
          :loading="isRefreshing"
        >
          刷新
        </a-button>
      </template>
      <a-table
        :columns="columns"
        :data-source="subscribers"
        :loading="isLoading || isRefreshing"
        :pagination="false"
        rowKey="mid"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'name'">
            <a-space>
              <img 
                v-if="record.face" 
                :src="record.face" 
                :alt="record.name"
                style="width: 24px; height: 24px; border-radius: 50%"
              />
              {{ record.name || '未获取到名称' }}
            </a-space>
          </template>
          <template v-if="column.key === 'status'">
            <a-tag :color="record.status === '1' ? 'success' : 'default'">
              {{ record.status === '1' ? '直播中' : '未开播' }}
            </a-tag>
          </template>
          <template v-if="column.key === 'actions'">
            <a-popconfirm
              title="确定要移除吗？"
              @confirm="() => handleRemove(record.mid)"
              :disabled="removingMids.includes(record.mid)"
            >
              <a-button 
                type="link" 
                danger
                :loading="removingMids.includes(record.mid)"
                :disabled="removingMids.includes(record.mid)"
              >
                移除
              </a-button>
            </a-popconfirm>
          </template>
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useQuery, useQueryClient } from '@tanstack/vue-query';
import { message } from 'ant-design-vue';
import request from '@/utils/request';
import type { Subscriber } from '@/types/api';
import { QueryKeys } from '@/constants/queryKeys';

const newMid = ref('');
const isAdding = ref(false);
const isRefreshing = ref(false);
const removingMids = ref<string[]>([]);
const subscribers = ref<Subscriber[]>([]);

const columns = [
  {
    title: 'UID',
    dataIndex: 'mid',
    key: 'mid',
    width: 120,
  },
  {
    title: '主播',
    dataIndex: 'name',
    key: 'name',
    width: 200,
  },
  {
    title: '状态',
    key: 'status',
    width: 100,
  },
  {
    title: '操作',
    key: 'actions',
    width: 100,
  },
];

const queryClient = useQueryClient();

const { isLoading, refetch } = useQuery({
  queryKey: ['subscribers'],
  queryFn: async () => {
    try {
      const response = await request.get<Subscriber[]>('/monitor/subscribers');
      subscribers.value = response;
      return response;
    } catch (error: any) {
      message.error('获取订阅列表失败');
      return [];
    }
  },
  refetchInterval: 30000,
});

const handleRefresh = async () => {
  if (isRefreshing.value) return;
  isRefreshing.value = true;
  try {
    await refetch();
    message.success('刷新成功');
  } catch (error) {
    message.error('刷新失败');
  } finally {
    isRefreshing.value = false;
  }
};

const handleAdd = async () => {
  if (isAdding.value) return;
  
  if (!newMid.value) {
    message.error('请输入UID');
    return;
  }
  if (!/^\d+$/.test(newMid.value)) {
    message.error('UID必须是数字');
    return;
  }

  // 检查是否已存在
  const existingSubscriber = subscribers.value?.find(s => s.mid === newMid.value);
  if (existingSubscriber) {
    message.warning(`${existingSubscriber.name || newMid.value} 已在监控列表中`);
    newMid.value = '';
    return;
  }

  isAdding.value = true;
  try {
    const response = await request.post(`/monitor/subscribers/${newMid.value}`);
    if (response.message?.includes('已在监控列表中')) {
      message.warning(`${response.name || newMid.value} 已在监控列表中`);
    } else {
      message.success('添加成功');
      // 同时刷新订阅列表和监控状态
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: QueryKeys.SUBSCRIBERS }),
        queryClient.invalidateQueries({ queryKey: QueryKeys.MONITOR_STATUS })
      ]);
    }
    newMid.value = '';
  } catch (error: any) {
    message.error(error.response?.data?.detail || '添加失败');
  } finally {
    isAdding.value = false;
  }
};

const handleRemove = async (mid: string) => {
  if (removingMids.value.includes(mid)) return;
  
  removingMids.value.push(mid);
  try {
    await request.delete(`/monitor/subscribers/${mid}`);
    message.success('移除成功');
    // 同时刷新订阅列表和监控状态
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: QueryKeys.SUBSCRIBERS }),
      queryClient.invalidateQueries({ queryKey: QueryKeys.MONITOR_STATUS })
    ]);
  } catch (error: any) {
    console.error('移除失败:', error);
    message.error(error.response?.data?.detail || '移除失败');
  } finally {
    removingMids.value = removingMids.value.filter(id => id !== mid);
  }
};
</script>

<style scoped>
.subscribers {
  max-width: 1200px;
  margin: 0 auto;
}
</style>
